### ISSUE TITLE
Unclear how to proceed after generating client

### ISSUE THREAD

**Issue by peterklingelhofer** [resonatecoop/user-api-client#1]
```sh
swagger generate client -f ./user.swagger.json -a "user-api-client"
```
Seems to work fine, and I get `Generation completed!`.

It says below that:
```sh
For this generation to compile you need to have some packages in your GOPATH:

        * github.com/go-openapi/errors
        * github.com/go-openapi/runtime
        * github.com/go-openapi/runtime/client
        * github.com/go-openapi/strfmt

You can get these now with: go get -u -f ./...
```

I ran `go get -u -f ./...` and that seemed to complete successfully.

After that, in the directions, there is an `Example` section, but it's unclear how the developer should proceed after that to get things up and running.

**Comment by auggod** [comment]
Not 100% sure but I think I read somewhere that it's expected and It's ok to ignore.
